name: Run Static Analysis

on: push

jobs:
  build-the-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Set up the package cache
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

  run-the-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Set up the package cache
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run the linter
        run: npm run lint

  check-the-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Set up the package cache
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run the linter
        run: npm run format:check

  run-the-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Set up the package cache
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run the unit tests
        run: npm test

  run-the-end-to-end-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Checkout the end to end tests
        uses: actions/checkout@v4
        with:
          repository: "fortymm/web-client-end-to-end-tests"
          path: web-client-end-to-end-tests

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Install the server dependencies
        run: npm ci

      - name: Build the server
        run: npm run build

      - name: Start the server
        run: npm run preview &

      - name: Install the test dependencies
        working-directory: web-client-end-to-end-tests
        run: npm ci

      - name: Install the test browsers
        working-directory: web-client-end-to-end-tests
        run: npx playwright install --with-deps

      - name: Run the end to end tests
        working-directory: web-client-end-to-end-tests
        run: npx playwright test
