name: Run Static Analysis

on: push

jobs:
  build-the-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Set up the package cache
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

  run-the-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Set up the package cache
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run the linter
        run: npm run lint

  check-the-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Set up the package cache
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run the linter
        run: npm run format:check

  run-the-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Set up the package cache
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run the unit tests
        run: npm test
